// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLW1oUDUIPfZKgvYE3NCOg3OkBV3TPzA',
    appId: '1:713568186940:web:59752d2d2b682a8ea28939',
    messagingSenderId: '713568186940',
    projectId: 'chatapp-1d7de',
    authDomain: 'chatapp-1d7de.firebaseapp.com',
    storageBucket: 'chatapp-1d7de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYepy7pR9FNXrKEodsJFOz6X9zKvsclPg',
    appId: '1:713568186940:android:ff8db16c8e445ed9a28939',
    messagingSenderId: '713568186940',
    projectId: 'chatapp-1d7de',
    storageBucket: 'chatapp-1d7de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5R4I9pjdk3XDPD183oLAjpfKqal_OtBY',
    appId: '1:713568186940:ios:a8581429d61707f3a28939',
    messagingSenderId: '713568186940',
    projectId: 'chatapp-1d7de',
    storageBucket: 'chatapp-1d7de.firebasestorage.app',
    iosBundleId: 'com.example.supportChat',
  );
}
